### PR TITLE
Manual rebuild pytorch111

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Errors for reference:
```
2022-04-27T04:42:57.0549217Z   /home/conda/feedstock_root/build_artifacts/fcos_1651033968808/work/fcos/core/csrc/cuda/ROIAlign_cuda.cu(275): error: identifier "THCCeilDiv" is undefined
2022-04-27T04:42:57.0549841Z 
2022-04-27T04:42:57.0550629Z   /home/conda/feedstock_root/build_artifacts/fcos_1651033968808/work/fcos/core/csrc/cuda/ROIAlign_cuda.cu(275): error: no instance of overloaded function "std::min" matches the argument list
2022-04-27T04:42:57.0551843Z               argument types are: (<error-type>, long)
2022-04-27T04:42:57.0552307Z 
2022-04-27T04:42:57.0553010Z   /home/conda/feedstock_root/build_artifacts/fcos_1651033968808/work/fcos/core/csrc/cuda/ROIAlign_cuda.cu(279): error: identifier "THCudaCheck" is undefined
2022-04-27T04:42:57.0553604Z 
2022-04-27T04:42:57.0554271Z   /home/conda/feedstock_root/build_artifacts/fcos_1651033968808/work/fcos/core/csrc/cuda/ROIAlign_cuda.cu(297): error: identifier "THCudaCheck" is undefined
2022-04-27T04:42:57.0554858Z 
2022-04-27T04:42:57.0555505Z   /home/conda/feedstock_root/build_artifacts/fcos_1651033968808/work/fcos/core/csrc/cuda/ROIAlign_cuda.cu(320): error: identifier "THCCeilDiv" is undefined
2022-04-27T04:42:57.0556115Z 
2022-04-27T04:42:57.0556852Z   /home/conda/feedstock_root/build_artifacts/fcos_1651033968808/work/fcos/core/csrc/cuda/ROIAlign_cuda.cu(320): error: no instance of overloaded function "std::min" matches the argument list
2022-04-27T04:42:57.0558005Z               argument types are: (<error-type>, long)
2022-04-27T04:42:57.0617584Z 
2022-04-27T04:42:57.0626844Z   /home/conda/feedstock_root/build_artifacts/fcos_1651033968808/work/fcos/core/csrc/cuda/ROIAlign_cuda.cu(325): error: identifier "THCudaCheck" is undefined
2022-04-27T04:42:57.0632822Z 
2022-04-27T04:42:57.0639937Z   /home/conda/feedstock_root/build_artifacts/fcos_1651033968808/work/fcos/core/csrc/cuda/ROIAlign_cuda.cu(344): error: identifier "THCudaCheck" is undefined
```

Potential fixes: https://github.com/NVIDIA/apex/pull/1191 and https://github.com/pytorch/pytorch/pull/65472

**Comment by mikemhenry** [comment]
For future me and anyone else who runs into this issue, this comment should have everything you need https://github.com/pytorch/pytorch/issues/72807#issuecomment-1039505288

**Comment by mikemhenry** [comment]
Okay everything is green! I'm going to re-build it again and this time add `store_build_artifacts: true` so we can test the package :tada:

**Comment by btalb** [comment]
Looks good, merged in. Thanks @mikemhenry.

**Pull request merged**
